version: "3.9"

services:
  gateway:
    build:
      context: ../Gateway
    container_name: gateway
    ports:
      - "3001:3001"
    env_file:
      - .env
      - .env.gateway
    networks:
      - app_network

  users:
    build:
      context: ../Users
    container_name: users
    ports:
      - "3002:3002"
    env_file:
      - .env
      - .env.users
    networks:
      - app_network

  movies:
    build:
      context: ../Movies
    container_name: movies
    ports:
      - "3003:3003"
    env_file:
      - .env
      - .env.movies
    networks:
      - app_network

  payment:
    build:
      context: ../Payment
    container_name: payment
    ports:
      - "3004:3004"
    env_file:
      - .env
      - .env.payment
    networks:
      - app_network

  profile:
    build:
      context: ../Profile
    container_name: profile
    ports:
      - "3005:3005"
    env_file:
      - .env
      - .env.profile
    networks:
      - app_network

  streaming:
    build:
      context: ../Streaming
    container_name: streaming
    ports:
      - "3006:3006"
    env_file:
      - .env
      - .env.streaming
    networks:
      - app_network

  client:
    build:
      context: ../Client/Netflix
    container_name: client
    ports:
      - "5173:5173"
    env_file:
      - .env
      - .env.client
    networks:
      - app_network
    depends_on:
      - gateway

networks:
  app_network:
    driver: bridge
